version: '2'
services:
    app:
        restart: always
        build: .
        command: "gunicorn -b 0.0.0.0:5000 metadome.application:app"
        environment:
            - FLASK_APP=metadome/application.py
        ports:
            - "5000:5000"
        depends_on:
            - db
            - celery
        volumes:
            - .:/usr/src/app
            - data:/usr/data
            - clinvar:/usr/data/ClinVar
            - gencode:/usr/data/Gencode
            - gnomad:/usr/data/gnoMAD
            - pfam:/usr/data/PFAM
            - uniprot:/usr/data/UniProt
            - /usr/bin/docker:/usr/bin/docker               # Point the local file to where your docker executable is located
            - /var/run/docker.sock:/var/run/docker.sock     # Point the local file to where your docker.sock is located
            - interpro_temp:/usr/interpro_temp
    celery:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        command: celery -A metadome.application:celery worker --loglevel=info
        environment:
            - C_FORCE_ROOT=1
        depends_on:
            - db
            - redis
        volumes:
            - .:/usr/src/app
            - data:/usr/data
            - clinvar:/usr/data/ClinVar
            - gencode:/usr/data/Gencode
            - gnomad:/usr/data/gnoMAD
            - pfam:/usr/data/PFAM
            - uniprot:/usr/data/UniProt
            - /usr/bin/docker:/usr/bin/docker               # Point the local file to where your docker executable is located
            - /var/run/docker.sock:/var/run/docker.sock     # Point the local file to where your docker.sock is located
            - interpro_temp:/usr/interpro_temp
    db:
        restart: always
        image: postgres
        environment:
           - ./metadome/postgres_credentials.py
        ports:
          - "5432:5432"
        volumes:
            - metadome_postgres_db:/var/lib/postgresql/data
    redis:
        restart: always
        image: redis
        ports:
          - "6379:6379"
volumes:
   data: 
      driver_opts:
        type: none
        # Please set the 'device' here to a local folder you are okay with MetaDome to create additional files and folders
        device: <ABSOLUTE PATH>
        o: bind
   clinvar:
      driver_opts:
        type: none
        # Please set the 'device' here to a local folder to where your ClinVar vcf is stored
        device: <ABSOLUTE PATH>
        o: bind
   gencode:
      driver_opts:
        type: none
        # Please set the 'device' here to a local folder to where your Gencode files are stored
        device: <ABSOLUTE PATH>
        o: bind
   gnomad:
      driver_opts:
        type: none
        # Please set the 'device' here to a local folder to where your gnomAD vcf is stored
        device: <ABSOLUTE PATH>
        o: bind
   pfam: 
      driver_opts:
        type: none
        # Please set the 'device' here to a local folder to where your PFAM is located
        device: <ABSOLUTE PATH>
        o: bind
   uniprot: 
      driver_opts:
        type: none
        # Please set the 'device' here to a local folder to where your UniProt is located
        device: <ABSOLUTE PATH>
        o: bind
   metadome_postgres_db:
      driver_opts:
        type: none
        # Please set the 'device' here to a local folder you are okay with MetaDome creating a postgres database
        device: <ABSOLUTE PATH>
        o: bind
   interpro_temp: # Do not change this, this should be the last line with nothing behind it.