version: '2'
services:
    app:
        build: .
        command: watchmedo auto-restart -d /usr/src/app -p "*" -D -R -- flask run -h 0.0.0.0
        environment:
            - FLASK_APP=metadom/application.py
        ports:
            - "5000:5000"
        volumes:
            - .:/usr/src/app
            - interpro_temp:/usr/interpro_temp
            - ~/data:/usr/data
            - /usr/bin/docker:/usr/bin/docker
            - /var/run/docker.sock:/var/run/docker.sock
