version: '2'
services:
    app:
        build: .
        command: "flask run --host=0.0.0.0"
        environment:
            - FLASK_APP=metadom/application.py
        ports:
            - "5000:5000"
        volumes:
            - .:/app
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: example
