version: '2'
services:
    app:
        build: .
        command: "flask run --host=0.0.0.0"
        environment:
            - FLASK_APP=metadome/application.py
        ports:
            - "5000:5000"
        depends_on:
            - db
        volumes:                                            # formatted as <local file/directory>:<docker file/directory>, only change the local directories if needed
            - .:/usr/src/app                                # This points to the current code directory, needed to run the MetaDome server, do not change
            - ~/data:/usr/data                              # Please set the local folder you are okay with MetaDome to create additional files and folders
            - ~/data/ClinVar/:/usr/data/ClinVar             # Please set the local folder to where your ClinVar vcf is stored
            - ~/data/Gencode/:/usr/data/Gencode             # Please set the local folder to where your Gencode files are stored
            - ~/data/gnomAD/:/usr/data/gnoMAD               # Please set the local folder to where your gnomAD vcf is stored
            - ~/data/PFAM/:/usr/data/PFAM                   # Please set the local folder to where your PFAM is located
            - ~/data/UniProt/:/usr/data/UniProt             # Please set the local folder to where your UniProt is located
            - /usr/bin/docker:/usr/bin/docker               # Point the local file to where your docker executable is located
            - /var/run/docker.sock:/var/run/docker.sock     # Point the local file to where your docker.sock is located
            - interpro_temp:/usr/interpro_temp              # This points to the local interpro volume, specified below. Do not change
    db:
        image: postgres
        environment:
           - POSTGRES_USER=metadom_user
           - POSTGRES_PASSWORD=example
volumes:
   interpro_temp: