version: '2'
services:
    app:
        restart: always
        build: .
        command: "gunicorn -b 0.0.0.0:5000 metadome.application:app"
        environment:
            - FLASK_APP=metadome/application.py
        ports:
            - "5000:5000"
        depends_on:
            - db
            - celery
        volumes:
            - .:/usr/src/app
            - /srv/metadome/data:/usr/data
            - /srv/metadome/data/ClinVar:/usr/data/ClinVar
            - /srv/metadome/data/Gencode:/usr/data/Gencode
            - /srv/metadome/data/gnoMAD:/usr/data/gnoMAD
            - /srv/metadome/data/PFAM:/usr/data/PFAM
            - /srv/metadome/data/UniProt:/usr/data/UniProt
    celery:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        command: celery -A metadome.application:celery worker --loglevel=info
        environment:
            - C_FORCE_ROOT=1
        depends_on:
            - db
            - redis
            - rabbitmq
        volumes:
            - .:/usr/src/app
            - /srv/metadome/data:/usr/data
            - /srv/metadome/data/ClinVar:/usr/data/ClinVar
            - /srv/metadome/data/Gencode:/usr/data/Gencode
            - /srv/metadome/data/gnoMAD:/usr/data/gnoMAD
            - /srv/metadome/data/PFAM:/usr/data/PFAM
            - /srv/metadome/data/UniProt:/usr/data/UniProt
    db:
        restart: always
        image: postgres:10
        environment:
           - ./metadome/postgres_credentials.py
        ports:
          - "5432:5432"
        volumes:
            - /srv/metadome/postgres:/var/lib/postgresql/data
    redis:
        restart: always
        image: redis:4.0
        ports:
          - "6379:6379"
    rabbitmq:
        restart: always
        image: rabbitmq:3.7
        ports:
          - "15672:15672"
